GraphView 및 MotionMeasurementManager 구현
Judy-999/ios-wanted-GyroData pull request #13
Opened 2022-12-28 06:42 UTC by Judy-999

## Motivation
- #6

## Changes
- GraphView에 기본 격자 무늬 그림 구현
- 그림 조각이 되는 GraphSegment 구현
- MotionMeasurementManager를 SingleTon으로 구현 (현재는 가속도만 측정 가능)
- 측정 버튼으로 시작 및 정지 버튼으로 멈추도록 action 추가

## Screen Shots
<img src="https://user-images.githubusercontent.com/102353787/209764130-6e74f397-438c-4434-8025-77c9826ac2c5.gif" width="300" height="600" />

## To Reviewers
예제 프로젝트를 기반으로 구현했는데 아직 세부사항은 모두 만족하진 않습니다..! 더 이해가 필요할 것 같네요.

스크린샷은 역시 다른 프로젝트에 옮겨서 핸드폰으로 직접 실행한 영상입니다. 
이 프로젝트로 해보려고 했는데 개발팀을 적용해야 돼서 일단 다른 걸로 실험해봤습니다! 
버튼 누르는게 안보이지만 측정버튼 누르면 시작하고 정지버튼 눌러서 멈췄습니다. 
그리고 영상이 길어서 다 못찍었는데 60초 지나면 끝까지 그려지고 멈춥니다.

브랜치 이름이 잘못됐어서 바꿨더니 PR이 닫힌듯 하네요..! 다시 올립니다 🥲

2022-12-28 11:37 UTC, Judy-999 commented
## Screen Shots
<img src="https://user-images.githubusercontent.com/102353787/209805940-c7441c85-e7dd-4606-a695-98bf666b7802.gif" width="300" height="600" />

## Changes
- 그래프 그려지는 속도 빠르게 변경
- 끝까지 그려질 수 있도록 변경
-  Gyro 측정 로직 구현 (변경해서 측정하는 것은 이후 뷰에서 작업)
- 정지하면 멈추는 것이 아니라 초기화하도록 변경

## Screen Shots
쪼금 빨라진거 같은데 더 빠르게 할 수도 있습니다! 대신 선들이 더 끊겨 보이는 느낌이기니 합니다.

2022-12-28 12:24 UTC, llghdud921 requested changes
🐰 고생많으셨어요!!
아래 코멘트 남겨두었습니다 👍

그리고 혹시 만드신 파일들 폴더에 넣을 수 있을까요? 정리가 필요할 것 같습니다!!

2022-12-28 12:24 UTC, llghdud921 commented on GyroData/MotionMeasurementManager.swift
> +    private init() {}
MotionMeasurementManager를 SingleTon으로 구현하신 이유가 있을까요?

2022-12-28 12:24 UTC, llghdud921 commented on GyroData/MotionMeasurementManager.swift
> +        var timeCount = Double.zero
현재 `startAccelerometers()` 와 `startGyro()` 두가지로 분리되어 있는데요!
motionType 열거형을 이용해서 하나의 메소드로 구현할 수 있지않을까 생각이 듭니다 ☺️

2022-12-28 12:59 UTC, Judy-999 commented on GyroData/MotionMeasurementManager.swift
> +    private init() {}
CMMotionManager 공식 문서에서 `Create only one CMMotionManager object for your app.`이라고 되어 있어서 하나의 객체만 가지려면 싱글톤이여야 할 것 같아 이렇게 구현했습니다!

[CMMotionManager](https://developer.apple.com/documentation/coremotion/cmmotionmanager)

2022-12-28 13:00 UTC, Judy-999 commented on GyroData/MotionMeasurementManager.swift
> +        var timeCount = Double.zero
안그래도 저도 로직이 너무 비슷해서 고민했는데 합쳐보겠습니다!

2022-12-28 14:16 UTC, llghdud921 commented on GyroData/MotionMeasurementManager.swift
> +    private init() {}
오호!! 이런 중요한 이유가 있었네요 👍
너무 좋습니다 ☺️

2022-12-29 02:40 UTC, Judy-999 commented
## Screen Shots
**측정 -> 정지 -> 측정**
<img src="https://user-images.githubusercontent.com/102353787/209896121-0224c2db-94fa-4e22-b750-875899e5154c.gif" width="300" height="600" />

## Changes
- 파일을 그룹으로 분류
- 그래프에 x, y, z를 표시하는 레이블 추가
- 측정 로직을 MotionType을 사용해 분기 처리
- 측정 시 그래프를 초기화하고 시작

## Screen Shots
파일 분류를 해보긴 했는데 맞게 정리했는지 잘 모르겠네요..!

2022-12-29 03:47 UTC, llghdud921 approved these changes
우와!! 너무 좋습니다!! 
🐰👍

2022-12-29 04:15 UTC, merged